// <auto-generated />
using System;
using ControleAusencia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleAusencia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407232854_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControleAusencia.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "joao@escola.com",
                            Nome = "João Silva"
                        },
                        new
                        {
                            Id = 2,
                            Email = "maria@escola.com",
                            Nome = "Maria Souza"
                        });
                });

            modelBuilder.Entity("ControleAusencia.Models.RegistroFalta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<int>("QuantidadeFaltas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("RegistrosFaltas");
                });

            modelBuilder.Entity("ControleAusencia.Models.RegistroFalta", b =>
                {
                    b.HasOne("ControleAusencia.Models.Aluno", "Aluno")
                        .WithMany("RegistrosFaltas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("ControleAusencia.Models.Aluno", b =>
                {
                    b.Navigation("RegistrosFaltas");
                });
#pragma warning restore 612, 618
        }
    }
}
